Repository wjk/MSIExtractApp, pull requests merged in 2021-01, with the labels that each got.

#68 Allow project to run outside an AppX container
  src/MSIExtract/App.xaml.cs
Labels: feature

#66 Fix reading binary columns
  src/MSIExtract.Core/Msi/ViewWrapper.cs
Labels: bugfix

#67 Add filter option to ExtractFilesView
  src/MSIExtract/Model/AppModel.cs
  src/MSIExtract/Views/ExtractFilesView.xaml
Labels: bump-minor-version, feature

#69 Add a new tab showing all MSI tables present
  src/MSIExtract.Core/Msi/MsiDataContainer.cs
  src/MSIExtract.Core/Msi/TableWithData.cs
  src/MSIExtract.Core/Msi/TableWrapper.cs
  src/MSIExtract/Model/AppModel.cs
  src/MSIExtract/Views/MainWindow.xaml
  src/MSIExtract/Views/TableView.xaml
  src/MSIExtract/Views/TableView.xaml.cs
Labels: bump-major-version, feature

#71 Highlight search terms
  legal/ThirdPartyNotices.md
  src/MSIExtract/App.xaml
  src/MSIExtract/Controls/HighlightTermBehavior.cs
  src/MSIExtract/Model/AppModel.cs
  src/MSIExtract/Theme/HighlightTextStyle.xaml
  src/MSIExtract/Views/ExtractFilesView.xaml
  src/MSIExtract/Views/ExtractFilesView.xaml.cs
  src/MSIExtract/Views/TableView.xaml.cs
Labels: feature
